// desktop/src/vue/components/layout/MadcopTitlebar.vue
<script setup lang="ts">
// v3.0 — MadCop Titlebar (Vue 3)
// 32px height, center command input, right side controls.

import { ref } from 'vue'

const props = defineProps<{ projectName?: string }>()
const emit = defineEmits<{ (e: 'command', cmd: string): void }>()

const cmd = ref('')

function onEnter() {
  const v = cmd.value.trim()
  if (!v) return
  emit('command', v)
  cmd.value = ''
}
</script>

<template>
  <div class="madcop-titlebar">
    <div class="madcop-titlebar__left">
      <span class="madcop-titlebar__brand">MADCOP</span>
      <span v-if="projectName" class="madcop-titlebar__sep">/</span>
      <span v-if="projectName" class="madcop-titlebar__proj">{{ projectName }}</span>
    </div>

    <div class="madcop-titlebar__center">
      <div class="madcop-titlebar__cmd">
        <span class="madcop-titlebar__cmd-icon">⌕</span>
        <input
          v-model="cmd"
          @keydown.enter="onEnter"
          type="text"
          placeholder="执行命令 — 选模型、写提示、跳转"
          class="madcop-titlebar__cmd-input"
        />
        <kbd class="madcop-titlebar__cmd-kbd">⌘K</kbd>
      </div>
    </div>

    <div class="madcop-titlebar__right">
      <button class="madcop-titlebar__btn" @click="emit('command', 'appearance:toggle')">主题</button>
      <button class="madcop-titlebar__btn" @click="emit('command', 'settings:open')">设置</button>
    </div>
  </div>
</template>

<style scoped>
.madcop-titlebar {
  width: 100%; height: 100%;
  display: flex; align-items: center;
  padding: 0 12px; gap: 12px;
  background: var(--madcop-panel-raised);
  -webkit-app-region: drag;
}
.madcop-titlebar__left  { display: flex; align-items: center; gap: 8px; min-width: 200px; }
.madcop-titlebar__center { flex: 1; display: flex; justify-content: center; }
.madcop-titlebar__right { min-width: 200px; display: flex; justify-content: flex-end; gap: 8px; }

.madcop-titlebar__brand {
  font-family: 'Geist Mono', monospace; font-size: 11px; color: var(--madcop-ink-muted);
  letter-spacing: 0.02em;
}
.madcop-titlebar__sep  { color: var(--madcop-line); }
.madcop-titlebar__proj { font-size: 13px; color: var(--madcop-ink); }

.madcop-titlebar__cmd {
  display: flex; align-items: center; gap: 8px;
  width: 320px; padding: 4px 10px;
  border: 1.5px solid var(--madcop-line);
  background: var(--madcop-panel-sunken);
}
.madcop-titlebar__cmd-icon  { color: var(--madcop-ink-muted); font-family: 'Geist Mono', monospace; font-size: 12px; }
.madcop-titlebar__cmd-input { flex: 1; border: none; outline: none; background: transparent; font-size: 13px; color: var(--madcop-ink); }
.madcop-titlebar__cmd-kbd  { font-size: 10px; color: var(--madcop-ink-muted); border: 1px solid var(--madcop-line); padding: 1px 4px; font-family: 'Geist Mono', monospace; }

.madcop-titlebar__btn {
  padding: 4px 10px; border: 1.5px solid var(--madcop-line);
  background: var(--madcop-panel-raised); color: var(--madcop-ink-muted);
  font-size: 11px; font-family: 'Geist Mono', monospace; cursor: pointer;
  -webkit-app-region: no-drag;
}
</style>

// desktop/src/components/layout/MadcopTitlebar.tsx
// v3.0 — MadCop title bar.
//
// The previous TitleBar dragged a 40px row with traffic-light
// buttons on the right and a "New Project" menu. The new one is
// flatter: 32px, a small left-side wordmark, a center command input
// (jump-to / command-palette later), and macOS window controls on
// the right (kept the same for now).

import { useState } from 'react'
import { madcop, icon } from '../../foundations/tokens'

interface MadcopTitlebarProps {
  projectName?: string
  onCommand?: (cmd: string) => void
}

export function MadcopTitlebar({ projectName, onCommand }: MadcopTitlebarProps) {
  const [cmd, setCmd] = useState('')

  return (
    <div style={{
      width: '100%', height: '100%',
      display: 'flex', alignItems: 'center',
      padding: `0 ${madcop.space[3]}`,
      gap: madcop.space[3],
      background: 'var(--madcop-panel-raised)',
      WebkitAppRegion: 'drag',
    } as React.CSSProperties}>
      {/* Left: project + breadcrumb */}
      <div style={{ display: 'flex', alignItems: 'center', gap: madcop.space[2], minWidth: 200 }}>
        <span style={{
          fontFamily: madcop.type.family.mono, fontSize: 11, color: 'var(--madcop-ink-muted)',
          letterSpacing: madcop.type.tracking.wide,
        }}>MADCOP</span>
        {projectName && (
          <>
            <span style={{ color: 'var(--madcop-line)' }}>/</span>
            <span style={{ fontSize: madcop.type.size.body, color: 'var(--madcop-ink)' }}>{projectName}</span>
          </>
        )}
      </div>

      {/* Center: command input */}
      <div style={{
        flex: 1, display: 'flex', justifyContent: 'center',
      }}>
        <div style={{
          display: 'flex', alignItems: 'center', gap: madcop.space[2],
          width: 320, padding: `4px 10px`,
          border: `1.5px solid var(--madcop-line)`,
          background: 'var(--madcop-panel-sunken)',
        }}>
          <span style={{ color: 'var(--madcop-ink-muted)', fontFamily: madcop.type.family.mono, fontSize: 12 }}>{icon.find}</span>
          <input
            value={cmd}
            onChange={(e) => setCmd(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && cmd.trim()) {
                onCommand?.(cmd.trim())
                setCmd('')
              }
            }}
            placeholder="执行命令 — 选模型、写提示、跳转"
            style={{
              flex: 1, border: 'none', outline: 'none', background: 'transparent',
              fontSize: madcop.type.size.body, color: 'var(--madcop-ink)',
              fontFamily: madcop.type.family.ui,
            }}
          />
          <kbd style={{
            fontSize: 10, color: 'var(--madcop-ink-muted)',
            border: `1px solid var(--madcop-line)`, padding: '1px 4px',
            fontFamily: madcop.type.family.mono,
          }}>⌘K</kbd>
        </div>
      </div>

      {/* Right: window controls (macOS — handled by TitleBar) */}
      <div style={{ minWidth: 200, display: 'flex', justifyContent: 'flex-end', gap: madcop.space[2] }}>
        <button
          onClick={() => onCommand?.('appearance:toggle')}
          title="切换主题"
          style={{
            padding: '4px 10px', border: `1.5px solid var(--madcop-line)`,
            background: 'var(--madcop-panel-raised)', color: 'var(--madcop-ink-muted)',
            fontSize: 11, fontFamily: madcop.type.family.mono, cursor: 'pointer',
          }}
        >
          主题
        </button>
        <button
          onClick={() => onCommand?.('settings:open')}
          title="设置"
          style={{
            padding: '4px 10px', border: `1.5px solid var(--madcop-line)`,
            background: 'var(--madcop-panel-raised)', color: 'var(--madcop-ink-muted)',
            fontSize: 11, fontFamily: madcop.type.family.mono, cursor: 'pointer',
          }}
        >
          设置
        </button>
      </div>
    </div>
  )
}
