// desktop/src/vue/components/design/DesignCanvas.vue
<script setup lang="ts">
/**
 * v3.0 — MadCop Design Canvas (Vue 3 port)
 *
 * Native HTML5 drag-drop design editor. No external CSS, no Puck, no deps.
 * 1:1 port of src/design/DesignCanvas.tsx (React).
 *
 * Features:
 *  - 11 component types: Header / Paragraph / Button / Image / Input / Card /
 *    Flex / Grid / Section / Divider / Space
 *  - Click to select, edit fields in right panel
 *  - Drag to reorder children
 *  - 导出 .madcop (JSON) and 导入 .madcop
 *  - 保存 triggers onSave callback
 */

import { ref, computed, onMounted } from 'vue'

// ── Types ──────────────────────────────────────────────────────────────

export interface DesignItem {
  type: string
  props: Record<string, any>
  children?: DesignItem[]
}

export interface DesignData {
  root: { props: Record<string, any> }
  content: DesignItem[]
}

export interface FieldConfig {
  type: 'text' | 'textarea' | 'number' | 'select' | 'radio' | 'color'
  label: string
  options?: { label: string; value: string }[]
}

export interface ComponentConfig {
  fields: Record<string, FieldConfig>
  defaultProps: Record<string, any>
  isContainer?: boolean
  label: string
  render: (props: Record<string, any>) => string
}

// ── Component Registry ────────────────────────────────────────────────

const componentRegistry: Record<string, ComponentConfig> = {
  Header: {
    label: '标题',
    fields: {
      text: { type: 'text', label: '文字' },
      level: { type: 'select', label: '级别', options: [{ label: 'H1', value: '1' }, { label: 'H2', value: '2' }, { label: 'H3', value: '3' }] },
      color: { type: 'color', label: '颜色' },
      fontSize: { type: 'number', label: '字号' },
    },
    defaultProps: { text: '新标题', level: '2', fontSize: 24 },
    render: ({ text, level, color, fontSize }) => {
      const fontSizePx = `${fontSize || 24}px`
      const colorHex = color || '#1A1A1A'
      const text_ = text || '标题'
      const tag = `h${level || 2}`
      return `<${tag} style="margin: 0 0 8px 0; color: ${colorHex}; font-size: ${fontSizePx}; font-weight: 700;">${text_}</${tag}>`
    },
  },
  Paragraph: {
    label: '段落',
    fields: {
      text: { type: 'textarea', label: '文字' },
      color: { type: 'color', label: '颜色' },
      fontSize: { type: 'number', label: '字号' },
      textAlign: { type: 'select', label: '对齐', options: [{ label: '左', value: 'left' }, { label: '中', value: 'center' }, { label: '右', value: 'right' }] },
    },
    defaultProps: { text: '这是一段文字', fontSize: 14, textAlign: 'left' },
    render: ({ text, color, fontSize, textAlign }) =>
      `<p style="margin: 0 0 12px 0; font-size: ${fontSize || 14}px; line-height: 1.6; color: ${color || '#4B5563'}; text-align: ${textAlign || 'left'};">${text || '段落文字'}</p>`,
  },
  Button: {
    label: '按钮',
    fields: {
      text: { type: 'text', label: '文字' },
      variant: { type: 'select', label: '样式', options: [{ label: '主按钮', value: 'primary' }, { label: '次按钮', value: 'secondary' }] },
      color: { type: 'color', label: '颜色' },
    },
    defaultProps: { text: '按钮', variant: 'primary' },
    render: ({ text, variant, color }) => {
      const bg = variant === 'primary' ? (color || '#7C3AED') : '#E2E8F0'
      const fg = variant === 'primary' ? '#fff' : '#1A1A1A'
      return `<button style="padding: 10px 24px; border-radius: 6px; border: none; cursor: pointer; font-weight: 600; font-size: 14px; background: ${bg}; color: ${fg};">${text || '按钮'}</button>`
    },
  },
  Image: {
    label: '图片',
    fields: {
      src: { type: 'text', label: '图片地址' },
      width: { type: 'number', label: '宽度' },
      height: { type: 'number', label: '高度' },
    },
    defaultProps: { src: 'https://via.placeholder.com/300x200', width: 300, height: 200 },
    render: ({ src, width, height }) =>
      `<img src="${src || ''}" alt="" style="max-width: 100%; width: ${width || 300}px; height: ${height || 200}px; object-fit: cover; border-radius: 4px;" />`,
  },
  Input: {
    label: '输入框',
    fields: {
      placeholder: { type: 'text', label: '占位文字' },
      width: { type: 'number', label: '宽度' },
    },
    defaultProps: { placeholder: '请输入...', width: 300 },
    render: ({ placeholder, width }) =>
      `<input type="text" placeholder="${placeholder || ''}" style="padding: 10px 14px; border: 1px solid #D1D5DB; border-radius: 6px; font-size: 14px; width: ${width || 300}px;" />`,
  },
  Card: {
    label: '卡片',
    fields: {
      padding: { type: 'number', label: '内边距' },
      radius: { type: 'number', label: '圆角' },
    },
    defaultProps: { padding: 20, radius: 12 },
    isContainer: true,
    render: ({ padding, radius }, children = '') =>
      `<div style="background: #fff; border: 1px solid #E5E7EB; border-radius: ${radius || 12}px; padding: ${padding || 20}px; box-shadow: 0 1px 3px rgba(0,0,0,0.05);">${children}</div>`,
  },
  Flex: {
    label: '弹性布局',
    fields: {
      direction: { type: 'select', label: '方向', options: [{ label: '横向', value: 'row' }, { label: '纵向', value: 'column' }] },
      gap: { type: 'number', label: '间距' },
    },
    defaultProps: { direction: 'column', gap: 8 },
    isContainer: true,
    render: ({ direction, gap }, children = '') =>
      `<div style="display: flex; flex-direction: ${direction || 'column'}; gap: ${gap || 8}px;">${children}</div>`,
  },
  Grid: {
    label: '网格',
    fields: {
      columns: { type: 'number', label: '列数' },
      gap: { type: 'number', label: '间距' },
    },
    defaultProps: { columns: 2, gap: 12 },
    isContainer: true,
    render: ({ columns, gap }, children = '') =>
      `<div style="display: grid; grid-template-columns: repeat(${columns || 2}, 1fr); gap: ${gap || 12}px;">${children}</div>`,
  },
  Section: {
    label: '区块',
    fields: {
      padding: { type: 'number', label: '内边距' },
      bgColor: { type: 'color', label: '背景色' },
    },
    defaultProps: { padding: 40, bgColor: '#F9FAFB' },
    isContainer: true,
    render: ({ padding, bgColor }, children = '') =>
      `<section style="padding: ${padding || 40}px; background: ${bgColor || '#F9FAFB'};">${children}</section>`,
  },
  Divider: {
    label: '分割线',
    fields: {},
    defaultProps: {},
    render: () => `<hr style="margin: 16px 0; border: none; border-top: 1px solid #E5E7EB;" />`,
  },
  Space: {
    label: '间距',
    fields: {
      height: { type: 'number', label: '高度' },
    },
    defaultProps: { height: 20 },
    render: ({ height }) => `<div style="height: ${height || 20}px;"></div>`,
  },
}

// ── Empty data helper ───────────────────────────────────────────────

function emptyData(): DesignData {
  return {
    root: { props: { bgColor: '#FFFFFF', padding: 40 } },
    content: [],
  }
}

// ── Props ─────────────────────────────────────────────────────────────

const props = defineProps<{
  initialData: DesignData
}>()

const emit = defineEmits<{
  save: [data: DesignData]
}>()

// ── State ───────────────────────────────────────────────────────────

const data = ref<DesignData>(JSON.parse(JSON.stringify(props.initialData)) || emptyData())
const selectedIndex = ref<number | null>(null)
const draggingIndex = ref<number | null>(null)
const draggingType = ref<string | null>(null)
const fileInputRef = ref<HTMLInputElement | null>(null)

// History (undo/redo)
const history = ref<DesignData[]>([])
const historyIndex = ref(-1)

watch(
  () => data.value,
  (val) => {
    // Push to history (debounced)
    history.value.push(JSON.parse(JSON.stringify(val)))
    historyIndex.value = history.value.length - 1
  },
  { deep: true }
)

onMounted(() => {
  // Load initial data
  if (props.initialData) {
    data.value = JSON.parse(JSON.stringify(props.initialData))
  }
  history.value = [JSON.parse(JSON.stringify(data.value))]
  historyIndex.value = 0
})

// ── Selection ────────────────────────────────────────────────────────

const selectedItem = computed<DesignItem | null>(() => {
  if (selectedIndex.value === null) return null
  return data.value.content[selectedIndex.value] || null
})

function selectIndex(idx: number | null) {
  selectedIndex.value = idx
}

// ── Item actions ────────────────────────────────────────────────────

function addItem(type: string, atIndex?: number) {
  const cfg = componentRegistry[type]
  if (!cfg) return
  const newItem: DesignItem = { type, props: { ...cfg.defaultProps } }
  const items = data.value.content
  if (atIndex === undefined || atIndex >= items.length) {
    items.push(newItem)
  } else {
    items.splice(atIndex, 0, newItem)
  }
  selectIndex(items.length - 1)
}

function updateItem(idx: number, updates: Partial<DesignItem['props']>) {
  const item = data.value.content[idx]
  if (!item) return
  item.props = { ...item.props, ...updates }
}

function deleteItem(idx: number) {
  data.value.content.splice(idx, 1)
  if (selectedIndex.value === idx) selectIndex(null)
  else if (selectedIndex.value !== null && selectedIndex.value > idx) {
    selectedIndex.value--
  }
}

function duplicateItem(idx: number) {
  const item = data.value.content[idx]
  if (!item) return
  const copy = JSON.parse(JSON.stringify(item))
  data.value.content.splice(idx + 1, 0, copy)
}

// ── Drag-drop ────────────────────────────────────────────────────────

function onDragStart(e: DragEvent, type: string) {
  draggingType.value = type
  draggingIndex.value = null
  e.dataTransfer?.setData('text/plain', type)
}

function onItemDragStart(e: DragEvent, idx: number) {
  draggingIndex.value = idx
  draggingType.value = null
  e.dataTransfer?.setData('text/plain', String(idx))
  e.stopPropagation()
}

function onDragOver(e: DragEvent) {
  e.preventDefault()
}

function onDrop(e: DragEvent, atIndex?: number) {
  e.preventDefault()
  if (draggingType.value) {
    addItem(draggingType.value, atIndex)
  } else if (draggingIndex.value !== null) {
    // Reorder
    const fromIdx = draggingIndex.value
    let toIdx = atIndex
    if (toIdx === undefined) {
      data.value.content.push(data.value.content.splice(fromIdx, 1)[0])
    } else if (fromIdx !== toIdx) {
      const item = data.value.content.splice(fromIdx, 1)[0]
      data.value.content.splice(toIdx, 0, item)
      if (selectedIndex.value === fromIdx) selectedIndex.value = toIdx
    }
  }
  draggingType.value = null
  draggingIndex.value = null
}

// ── Undo/Redo ───────────────────────────────────────────────────────

function undo() {
  if (historyIndex.value > 0) {
    historyIndex.value--
    data.value = JSON.parse(JSON.stringify(history.value[historyIndex.value]))
  }
}
function redo() {
  if (historyIndex.value < history.value.length - 1) {
    historyIndex.value++
    data.value = JSON.parse(JSON.stringify(history.value[historyIndex.value]))
  }
}

// ── Export / Import .madcop ─────────────────────────────────────────

function exportMadcop() {
  const json = JSON.stringify(data.value, null, 2)
  const blob = new Blob([json], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `design-${Date.now()}.madcop`
  a.click()
  URL.revokeObjectURL(url)
}

function triggerImport() {
  fileInputRef.value?.click()
}

function importMadcop(e: Event) {
  const input = e.target as HTMLInputElement
  const file = input.files?.[0]
  if (!file) return
  const reader = new FileReader()
  reader.onload = (ev) => {
    try {
      const parsed = JSON.parse(ev.target?.result as string)
      if (parsed.root && Array.isArray(parsed.content)) {
        data.value = parsed
        history.value = [JSON.parse(JSON.stringify(data.value))]
        historyIndex.value = 0
      } else {
        alert('文件格式有误')
      }
    } catch {
      alert('解析失败')
    }
  }
  reader.readAsText(file)
  input.value = ''
}

function saveData() {
  emit('save', JSON.parse(JSON.stringify(data.value)))
}

// ── Render the content tree ─────────────────────────────────────────

function renderItem(item: DesignItem): string {
  const cfg = componentRegistry[item.type]
  if (!cfg) return ''
  const childHtml = item.children ? item.children.map(renderItem).join('') : ''
  return cfg.render(item.props, childHtml)
}

const contentHtml = computed(() => data.value.content.map(renderItem).join(''))
</script>

<template>
  <div class="flex h-full w-full">
    <!-- Left palette -->
    <div
      style="width: 200px; background: var(--color-surface-container-lowest); border-right: 1px solid var(--color-border); padding: 12px; flex-shrink: 0; overflow-y: auto;"
    >
      <div style="font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px; color: var(--color-text-tertiary); margin-bottom: 8px;">
        组件库
      </div>
      <div style="display: flex; flex-direction: column; gap: 6px;">
        <div
          v-for="(cfg, type) in componentRegistry"
          :key="type"
          draggable="true"
          @dragstart="onDragStart($event, type)"
          class="design-palette-item"
        >
          {{ cfg.label }}
        </div>
      </div>
      <div style="font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px; color: var(--color-text-tertiary); margin: 16px 0 8px;">
        操作
      </div>
      <div style="display: flex; flex-direction: column; gap: 6px;">
        <button
          @click="undo"
          style="padding: 6px 10px; background: var(--color-surface); border: 1px solid var(--color-border); border-radius: 4px; cursor: pointer; font-size: 12px; color: var(--color-text-primary);"
        >↶ 撤销</button>
        <button
          @click="redo"
          style="padding: 6px 10px; background: var(--color-surface); border: 1px solid var(--color-border); border-radius: 4px; cursor: pointer; font-size: 12px; color: var(--color-text-primary);"
        >↷ 重做</button>
        <button
          @click="triggerImport"
          style="padding: 6px 10px; background: var(--color-surface); border: 1px solid var(--color-border); border-radius: 4px; cursor: pointer; font-size: 12px; color: var(--color-text-primary);"
        >导入 .madcop</button>
        <button
          @click="exportMadcop"
          style="padding: 6px 10px; background: #7C3AED; border: none; border-radius: 4px; cursor: pointer; font-size: 12px; color: #fff; font-weight: 500;"
        >导出 .madcop</button>
        <button
          @click="saveData"
          style="padding: 6px 10px; background: var(--color-success, #10b981); border: none; border-radius: 4px; cursor: pointer; font-size: 12px; color: #fff; font-weight: 500;"
        >保存</button>
      </div>
      <input
        ref="fileInputRef"
        type="file"
        accept=".madcop,.json"
        style="display: none;"
        @change="importMadcop"
      />
    </div>

    <!-- Center canvas -->
    <div
      style="flex: 1; overflow: auto; padding: 32px; background: #E5E7EB;"
      @click="selectIndex(null)"
    >
      <div
        :style="{
          background: data.root.props.bgColor || '#FFFFFF',
          padding: (data.root.props.padding || 40) + 'px',
          minHeight: '100%',
          width: '800px',
          margin: '0 auto',
          boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
        }"
        @click.stop
      >
        <div
          v-if="data.content.length === 0"
          style="text-align: center; padding: 80px 20px; color: var(--color-text-tertiary); font-size: 14px;"
        >
          从左侧拖入组件开始设计
        </div>
        <div
          v-for="(item, idx) in data.content"
          :key="idx"
          :draggable="true"
          @dragstart.stop="onItemDragStart($event, idx)"
          @dragover="onDragOver"
          @drop.stop="onDrop($event, idx)"
          @click.stop="selectIndex(idx)"
          :class="['design-canvas-item', selectedIndex === idx ? 'design-canvas-item--selected' : '']"
          v-html="renderItem(item)"
        ></div>
      </div>
    </div>

    <!-- Right: property panel -->
    <div
      v-if="selectedItem"
      style="width: 280px; background: var(--color-surface-container-lowest); border-left: 1px solid var(--color-border); padding: 12px; flex-shrink: 0; overflow-y: auto;"
    >
      <div style="font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px; color: var(--color-text-tertiary); margin-bottom: 8px;">
        属性: {{ componentRegistry[selectedItem.type]?.label || selectedItem.type }}
      </div>
      <div
        v-for="(field, key) in componentRegistry[selectedItem.type]?.fields || {}"
        :key="key"
        style="margin-bottom: 10px;"
      >
        <label
          style="display: block; font-size: 11px; color: var(--color-text-secondary); margin-bottom: 4px;"
        >{{ field.label }}</label>
        <input
          v-if="field.type === 'text'"
          type="text"
          :value="selectedItem.props[key]"
          @input="(e) => updateItem(selectedIndex, { [key]: (e.target as HTMLInputElement).value })"
          style="width: 100%; padding: 6px 8px; border: 1px solid var(--color-border); border-radius: 4px; font-size: 12px; background: var(--color-surface); color: var(--color-text-primary);"
        />
        <textarea
          v-else-if="field.type === 'textarea'"
          :value="selectedItem.props[key]"
          @input="(e) => updateItem(selectedIndex, { [key]: (e.target as HTMLTextAreaElement).value })"
          rows="3"
          style="width: 100%; padding: 6px 8px; border: 1px solid var(--color-border); border-radius: 4px; font-size: 12px; resize: vertical; font-family: inherit; background: var(--color-surface); color: var(--color-text-primary);"
        ></textarea>
        <input
          v-else-if="field.type === 'number'"
          type="number"
          :value="selectedItem.props[key]"
          @input="(e) => updateItem(selectedIndex, { [key]: Number((e.target as HTMLInputElement).value) })"
          style="width: 100%; padding: 6px 8px; border: 1px solid var(--color-border); border-radius: 4px; font-size: 12px; background: var(--color-surface); color: var(--color-text-primary);"
        />
        <input
          v-else-if="field.type === 'color'"
          type="color"
          :value="selectedItem.props[key] || '#000000'"
          @input="(e) => updateItem(selectedIndex, { [key]: (e.target as HTMLInputElement).value })"
          style="width: 100%; height: 32px; padding: 2px; border: 1px solid var(--color-border); border-radius: 4px; background: var(--color-surface);"
        />
        <select
          v-else-if="field.type === 'select'"
          :value="selectedItem.props[key]"
          @change="(e) => updateItem(selectedIndex, { [key]: (e.target as HTMLSelectElement).value })"
          style="width: 100%; padding: 6px 8px; border: 1px solid var(--color-border); border-radius: 4px; font-size: 12px; background: var(--color-surface); color: var(--color-text-primary);"
        >
          <option v-for="opt in field.options" :key="opt.value" :value="opt.value">{{ opt.label }}</option>
        </select>
        <div v-else-if="field.type === 'radio'" style="display: flex; gap: 8px; flex-wrap: wrap;">
          <label
            v-for="opt in field.options"
            :key="opt.value"
            style="display: flex; align-items: center; gap: 4px; font-size: 12px;"
          >
            <input
              type="radio"
              :value="opt.value"
              :checked="selectedItem.props[key] === opt.value"
              @change="updateItem(selectedIndex, { [key]: opt.value })"
            />
            {{ opt.label }}
          </label>
        </div>
      </div>
      <div style="display: flex; gap: 6px; margin-top: 16px; padding-top: 12px; border-top: 1px solid var(--color-border);">
        <button
          @click="duplicateItem(selectedIndex)"
          style="flex: 1; padding: 6px 10px; background: var(--color-surface); border: 1px solid var(--color-border); border-radius: 4px; cursor: pointer; font-size: 12px; color: var(--color-text-primary);"
        >复制</button>
        <button
          @click="deleteItem(selectedIndex)"
          style="flex: 1; padding: 6px 10px; background: var(--color-surface); border: 1px solid color-mix(in srgb, var(--color-error) 30%, transparent); border-radius: 4px; cursor: pointer; font-size: 12px; color: var(--color-error);"
        >删除</button>
      </div>
    </div>
    <div
      v-else
      style="width: 280px; background: var(--color-surface-container-lowest); border-left: 1px solid var(--color-border); padding: 12px; flex-shrink: 0; display: flex; align-items: center; justify-content: center; color: var(--color-text-tertiary); font-size: 12px;"
    >
      选中组件后编辑属性
    </div>
  </div>
</template>

<style scoped>
.design-palette-item {
  padding: 8px 12px;
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: 4px;
  font-size: 12px;
  color: var(--color-text-primary);
  cursor: grab;
  user-select: none;
  transition: all 0.15s;
}
.design-palette-item:hover {
  background: var(--color-surface-container);
  border-color: #7C3AED;
  transform: translateX(2px);
}
.design-palette-item:active {
  cursor: grabbing;
}

.design-canvas-item {
  position: relative;
  padding: 4px;
  border-radius: 2px;
  cursor: pointer;
  transition: background 0.1s;
}
.design-canvas-item:hover {
  background: rgba(124, 58, 237, 0.05);
}
.design-canvas-item--selected {
  background: rgba(124, 58, 237, 0.08);
  outline: 2px solid #7C3AED;
  outline-offset: 2px;
}
</style>

// desktop/src/design/DesignCanvas.tsx
// v2.8.0 — MadCop Design Canvas (native, zero-dependency)
// Inspired by Puck's Data format (MIT, github.com/puckeditor/puck)
// but reimplemented with native HTML5 drag & drop + inline styles.
// No external CSS, no dnd-kit, no global style pollution.

import { useState, useCallback, useRef } from 'react'

// ── Types (compatible with Puck Data format) ────────────────────────── //

export interface DesignData {
  root: { props: Record<string, any> }
  content: DesignItem[]
  zones?: Record<string, DesignItem[]>
}

export interface DesignItem {
  type: string
  props: Record<string, any>
}

export interface FieldConfig {
  type: 'text' | 'textarea' | 'number' | 'select' | 'radio' | 'color'
  label: string
  options?: { label: string; value: string }[]
}

export interface ComponentConfig {
  render: (props: Record<string, any>) => React.ReactNode
  fields: Record<string, FieldConfig>
  defaultProps: Record<string, any>
}

export interface DesignConfig {
  root?: {
    fields: Record<string, FieldConfig>
    defaultProps: Record<string, any>
  }
  components: Record<string, ComponentConfig>
}

// ── Component registry ──────────────────────────────────────────────── //

const componentRegistry: Record<string, ComponentConfig> = {
  Header: {
    render: ({ text, level, color, fontSize }) => {
      const lvl = level || 2
      const Tag = `h${lvl}` as any
      return (
        <Tag style={{
          margin: '0 0 8px 0',
          color: color || '#1A1A1A',
          fontSize: fontSize || 24,
          fontWeight: 700,
        }}>
          {text || '标题'}
        </Tag>
      )
    },
    fields: {
      text: { type: 'text', label: '文字' },
      level: { type: 'select', label: '级别', options: [
        { label: 'H1', value: '1' },
        { label: 'H2', value: '2' },
        { label: 'H3', value: '3' },
      ] },
      color: { type: 'color', label: '颜色' },
      fontSize: { type: 'number', label: '字号' },
    },
    defaultProps: { text: '新标题', level: '2', fontSize: 24 },
  },
  Paragraph: {
    render: ({ text, color, fontSize }) => (
      <p style={{
        margin: '0 0 12px 0',
        fontSize: fontSize || 14,
        lineHeight: 1.6,
        color: color || '#4B5563',
      }}>
        {text || '段落文字'}
      </p>
    ),
    fields: {
      text: { type: 'textarea', label: '文字' },
      color: { type: 'color', label: '颜色' },
      fontSize: { type: 'number', label: '字号' },
    },
    defaultProps: { text: '这是一段文字', fontSize: 14 },
  },
  Button: {
    render: ({ text, variant, width, color }) => (
      <button
        style={{
          padding: '10px 24px',
          borderRadius: 6,
          border: 'none',
          cursor: 'pointer',
          fontWeight: 600,
          fontSize: 14,
          width: width ? `${width}px` : 'auto',
          background: variant === 'primary' ? (color || '#7C3AED') : '#E2E8F0',
          color: variant === 'primary' ? '#fff' : '#1A1A1A',
        }}
      >
        {text || '按钮'}
      </button>
    ),
    fields: {
      text: { type: 'text', label: '文字' },
      variant: { type: 'radio', label: '样式', options: [
        { label: '主要', value: 'primary' },
        { label: '次要', value: 'secondary' },
      ] },
      color: { type: 'color', label: '主色' },
      width: { type: 'number', label: '宽度' },
    },
    defaultProps: { text: '提交', variant: 'primary', color: '#7C3AED' },
  },
  Image: {
    render: ({ src, alt, width, height }) => (
      <img
        src={src || 'https://via.placeholder.com/400x200'}
        alt={alt || ''}
        style={{
          maxWidth: '100%',
          borderRadius: 8,
          width: width ? `${width}px` : 'auto',
          height: height ? `${height}px` : 'auto',
        }}
      />
    ),
    fields: {
      src: { type: 'text', label: '图片地址' },
      alt: { type: 'text', label: '替代文字' },
      width: { type: 'number', label: '宽度' },
      height: { type: 'number', label: '高度' },
    },
    defaultProps: { src: '', alt: '' },
  },
  Input: {
    render: ({ placeholder, width }) => (
      <input
        placeholder={placeholder || '输入...'}
        readOnly
        style={{
          padding: '10px 14px',
          border: '1px solid #D1D5DB',
          borderRadius: 6,
          fontSize: 14,
          width: width ? `${width}px` : '100%',
          outline: 'none',
          background: '#F9FAFB',
        }}
      />
    ),
    fields: {
      placeholder: { type: 'text', label: '占位文字' },
      width: { type: 'number', label: '宽度' },
    },
    defaultProps: { placeholder: '请输入...', width: 300 },
  },
  Card: {
    render: ({ padding, bgColor, borderWidth, borderColor, radius }) => (
      <div style={{
        padding: padding || 20,
        borderRadius: radius || 12,
        background: bgColor || '#F9FAFB',
        border: `${borderWidth || 1}px solid ${borderColor || '#E5E7EB'}`,
      }}>
        <span style={{ fontSize: 12, color: '#9CA3AF' }}>卡片容器</span>
      </div>
    ),
    fields: {
      padding: { type: 'number', label: '内边距' },
      bgColor: { type: 'color', label: '背景色' },
      radius: { type: 'number', label: '圆角' },
      borderWidth: { type: 'number', label: '边框粗细' },
      borderColor: { type: 'color', label: '边框色' },
    },
    defaultProps: { padding: 20, bgColor: '#F9FAFB', radius: 12, borderWidth: 1, borderColor: '#E5E7EB' },
  },
}

// ── Field renderer ──────────────────────────────────────────────────── //

function FieldEditor({
  field,
  value,
  onChange,
}: {
  field: FieldConfig
  value: any
  onChange: (v: any) => void
}) {
  const inputStyle: React.CSSProperties = {
    width: '100%',
    padding: '6px 10px',
    border: '1px solid #D1D5DB',
    borderRadius: 4,
    fontSize: 13,
    background: '#fff',
    boxSizing: 'border-box',
  }

  switch (field.type) {
    case 'textarea':
      return (
        <textarea
          value={value ?? ''}
          onChange={(e) => onChange(e.target.value)}
          rows={3}
          style={{ ...inputStyle, resize: 'vertical', fontFamily: 'inherit' }}
        />
      )
    case 'number':
      return (
        <input
          type="number"
          value={value ?? 0}
          onChange={(e) => onChange(Number(e.target.value) || 0)}
          style={inputStyle}
        />
      )
    case 'select':
      return (
        <select
          value={value ?? ''}
          onChange={(e) => onChange(e.target.value)}
          style={inputStyle}
        >
          {(field.options || []).map((opt) => (
            <option key={opt.value} value={opt.value}>{opt.label}</option>
          ))}
        </select>
      )
    case 'radio':
      return (
        <div style={{ display: 'flex', gap: 12 }}>
          {(field.options || []).map((opt) => (
            <label key={opt.value} style={{
              display: 'flex',
              alignItems: 'center',
              gap: 4,
              fontSize: 13,
              cursor: 'pointer',
            }}>
              <input
                type="radio"
                checked={value === opt.value}
                onChange={() => onChange(opt.value)}
              />
              {opt.label}
            </label>
          ))}
        </div>
      )
    case 'color':
      return (
        <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
          <input
            type="color"
            value={value || '#000000'}
            onChange={(e) => onChange(e.target.value)}
            style={{
              width: 32, height: 32,
              border: '1px solid #D1D5DB',
              borderRadius: 4,
              cursor: 'pointer',
              padding: 0,
            }}
          />
          <input
            type="text"
            value={value || ''}
            onChange={(e) => onChange(e.target.value)}
            style={{ ...inputStyle, width: 100 }}
          />
        </div>
      )
    default:
      return (
        <input
          type="text"
          value={value ?? ''}
          onChange={(e) => onChange(e.target.value)}
          style={inputStyle}
        />
      )
  }
}

// ── Main Canvas Component ───────────────────────────────────────────── //

interface DesignCanvasProps {
  initialData?: DesignData
  onSave?: (data: DesignData) => void
}

export function DesignCanvas({ initialData, onSave }: DesignCanvasProps) {
  const [data, setData] = useState<DesignData>(initialData || {
    root: { props: { bgColor: '#FFFFFF', padding: 40 } },
    content: [],
  })
  const [selectedIdx, setSelectedIdx] = useState<number | null>(null)
  const [dragIdx, setDragIdx] = useState<number | null>(null)
  const [dragOverIdx, setDragOverIdx] = useState<number | null>(null)
  const canvasRef = useRef<HTMLDivElement>(null)

  // Sync external data
  const lastInitial = useRef<DesignData | null>(null)
  if (initialData && initialData !== lastInitial.current) {
    lastInitial.current = initialData
    setData(initialData)
    setSelectedIdx(null)
  }

  // ── Mutations ── //
  const updateItem = useCallback((idx: number, props: Record<string, any>) => {
    setData((prev) => {
      const content = [...prev.content]
      content[idx] = { ...content[idx], props: { ...content[idx].props, ...props } }
      return { ...prev, content }
    })
  }, [])

  const deleteItem = useCallback((idx: number) => {
    setData((prev) => ({
      ...prev,
      content: prev.content.filter((_, i) => i !== idx),
    }))
    setSelectedIdx(null)
  }, [])

  const addComponent = useCallback((type: string) => {
    const cfg = componentRegistry[type]
    if (!cfg) return
    const newItem: DesignItem = { type, props: { ...cfg.defaultProps } }
    setData((prev) => ({
      ...prev,
      content: [...prev.content, newItem],
    }))
    setSelectedIdx(data.content.length) // select the new item
  }, [data.content.length])

  const reorder = useCallback((from: number, to: number) => {
    if (from === to) return
    setData((prev) => {
      const content = [...prev.content]
      const [moved] = content.splice(from, 1)
      content.splice(to, 0, moved)
      return { ...prev, content }
    })
    setSelectedIdx(to)
  }, [])

  // ── Drag handlers ── //
  const onDragStart = (idx: number) => setDragIdx(idx)
  const onDragOver = (e: React.DragEvent, idx: number) => {
    e.preventDefault()
    setDragOverIdx(idx)
  }
  const onDrop = (e: React.DragEvent, idx: number) => {
    e.preventDefault()
    if (dragIdx !== null) reorder(dragIdx, idx)
    setDragIdx(null)
    setDragOverIdx(null)
  }

  const bgColor = data.root?.props?.bgColor || '#FFFFFF'
  const padding = data.root?.props?.padding || 40
  const selectedItem = selectedIdx !== null ? data.content[selectedIdx] : null
  const selectedCfg = selectedItem ? componentRegistry[selectedItem.type] : null

  return (
    <div style={{ display: 'flex', height: '100%', background: '#F3F4F6' }}>
      {/* ── Left: Component palette ── */}
      <div style={{
        width: 180,
        flexShrink: 0,
        borderRight: '1px solid #E5E7EB',
        background: '#fff',
        padding: '12px 8px',
        overflowY: 'auto',
      }}>
        <div style={{
          fontSize: 11, fontWeight: 700, color: '#9CA3AF',
          textTransform: 'uppercase', letterSpacing: 0.5,
          marginBottom: 10, padding: '0 4px',
        }}>
          组件
        </div>
        {Object.keys(componentRegistry).map((type) => (
          <button
            key={type}
            onClick={() => addComponent(type)}
            style={{
              display: 'block',
              width: '100%',
              textAlign: 'left',
              padding: '8px 12px',
              marginBottom: 4,
              background: '#F9FAFB',
              border: '1px solid #E5E7EB',
              borderRadius: 6,
              cursor: 'pointer',
              fontSize: 13,
              color: '#374151',
              transition: 'background 0.15s',
            }}
            onMouseEnter={(e) => e.currentTarget.style.background = '#EEF2FF'}
            onMouseLeave={(e) => e.currentTarget.style.background = '#F9FAFB'}
          >
            {type}
          </button>
        ))}
      </div>

      {/* ── Center: Canvas ── */}
      <div
        ref={canvasRef}
        style={{
          flex: 1,
          overflowY: 'auto',
          padding: 24,
          display: 'flex',
          justifyContent: 'center',
        }}
      >
        <div
          style={{
            width: '100%',
            maxWidth: 720,
            minHeight: '100%',
            background: bgColor,
            borderRadius: 8,
            padding,
            boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
          }}
          onClick={() => setSelectedIdx(null)}
        >
          {data.content.length === 0 && (
            <div style={{
              textAlign: 'center',
              padding: '60px 20px',
              color: '#9CA3AF',
              fontSize: 14,
            }}>
              从左侧添加组件，或用 AI 生成设计
            </div>
          )}
          {data.content.map((item, idx) => {
            const cfg = componentRegistry[item.type]
            if (!cfg) return null
            const isSelected = selectedIdx === idx
            const isDragOver = dragOverIdx === idx
            return (
              <div
                key={idx}
                draggable
                onDragStart={() => onDragStart(idx)}
                onDragOver={(e) => onDragOver(e, idx)}
                onDrop={(e) => onDrop(e, idx)}
                onClick={(e) => {
                  e.stopPropagation()
                  setSelectedIdx(idx)
                }}
                style={{
                  marginBottom: 8,
                  padding: 4,
                  borderRadius: 4,
                  cursor: 'pointer',
                  border: isSelected
                    ? '2px solid #7C3AED'
                    : isDragOver
                    ? '2px dashed #A78BFA'
                    : '2px solid transparent',
                  transition: 'border-color 0.15s',
                }}
              >
                {/* Drag handle */}
                <div style={{
                  display: isSelected ? 'flex' : 'none',
                  justifyContent: 'flex-end',
                  fontSize: 10,
                  color: '#9CA3AF',
                  marginBottom: 2,
                }}>
                  ⠿ 拖拽排序
                </div>
                {cfg.render(item.props)}
                {/* Delete button */}
                {isSelected && (
                  <div style={{ textAlign: 'right', marginTop: 4 }}>
                    <button
                      onClick={(e) => {
                        e.stopPropagation()
                        deleteItem(idx)
                      }}
                      style={{
                        padding: '2px 8px',
                        fontSize: 11,
                        background: '#FEE2E2',
                        color: '#DC2626',
                        border: 'none',
                        borderRadius: 3,
                        cursor: 'pointer',
                      }}
                    >
                      删除
                    </button>
                  </div>
                )}
              </div>
            )
          })}
        </div>
      </div>

      {/* ── Right: Properties panel ── */}
      <div style={{
        width: 260,
        flexShrink: 0,
        borderLeft: '1px solid #E5E7EB',
        background: '#fff',
        padding: '12px 12px',
        overflowY: 'auto',
      }}>
        {selectedItem && selectedCfg ? (
          <>
            <div style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              marginBottom: 14,
            }}>
              <span style={{
                fontSize: 13, fontWeight: 700, color: '#1F2937',
              }}>
                {selectedItem.type} 属性
              </span>
              <span style={{
                fontSize: 11, color: '#9CA3AF',
              }}>
                #{(selectedIdx ?? 0) + 1}
              </span>
            </div>
            {Object.entries(selectedCfg.fields).map(([key, field]) => (
              <div key={key} style={{ marginBottom: 12 }}>
                <label style={{
                  display: 'block',
                  fontSize: 12,
                  color: '#6B7280',
                  marginBottom: 4,
                  fontWeight: 500,
                }}>
                  {field.label}
                </label>
                <FieldEditor
                  field={field}
                  value={selectedItem.props[key]}
                  onChange={(v) => {
                    if (selectedIdx !== null) {
                      updateItem(selectedIdx, { [key]: v })
                    }
                  }}
                />
              </div>
            ))}
          </>
        ) : (
          <>
            <div style={{
              fontSize: 11, fontWeight: 700, color: '#9CA3AF',
              textTransform: 'uppercase', letterSpacing: 0.5,
              marginBottom: 10,
            }}>
              画布设置
            </div>
            <div style={{ marginBottom: 12 }}>
              <label style={{
                display: 'block', fontSize: 12, color: '#6B7280', marginBottom: 4,
              }}>
                背景色
              </label>
              <FieldEditor
                field={{ type: 'color', label: '背景色' }}
                value={data.root?.props?.bgColor}
                onChange={(v) => {
                  setData((prev) => ({
                    ...prev,
                    root: { props: { ...prev.root.props, bgColor: v } },
                  }))
                }}
              />
            </div>
            <div style={{ marginBottom: 12 }}>
              <label style={{
                display: 'block', fontSize: 12, color: '#6B7280', marginBottom: 4,
              }}>
                内边距
              </label>
              <FieldEditor
                field={{ type: 'number', label: '内边距' }}
                value={data.root?.props?.padding}
                onChange={(v) => {
                  setData((prev) => ({
                    ...prev,
                    root: { props: { ...prev.root.props, padding: v } },
                  }))
                }}
              />
            </div>
            <div style={{
              marginTop: 20, padding: 10,
              background: '#F3F4F6', borderRadius: 6,
              fontSize: 12, color: '#9CA3AF', lineHeight: 1.5,
            }}>
              点击组件编辑属性
            </div>
          </>
        )}
      </div>

      {/* ── Bottom toolbar ── */}
      <div style={{
        position: 'absolute',
        bottom: 0,
        right: 0,
        display: 'flex',
        gap: 8,
        padding: '8px 16px',
      }}>
        <button
          onClick={() => {
            const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })
            const a = document.createElement('a')
            a.href = URL.createObjectURL(blob)
            a.download = `design-${Date.now()}.madcop`
            a.click()
          }}
          style={{
            padding: '6px 12px',
            background: 'rgba(255,255,255,0.9)',
            border: '1px solid #E5E7EB',
            borderRadius: 4,
            cursor: 'pointer',
            fontSize: 12,
            color: '#374151',
            backdropFilter: 'blur(4px)',
          }}
        >
          导出 .madcop
        </button>
        <button
          onClick={() => onSave?.(data)}
          style={{
            padding: '6px 12px',
            background: 'rgba(124,58,237,0.9)',
            color: '#fff',
            border: 'none',
            borderRadius: 4,
            cursor: 'pointer',
            fontSize: 12,
            fontWeight: 600,
            backdropFilter: 'blur(4px)',
          }}
        >
          保存
        </button>
      </div>
    </div>
  )
}

export type { Config as DesignConfig }
