// frontend/components/chat/MessageActionBar.tsx
'use client';

import { useState } from 'react';
import { Check, Copy } from 'lucide-react';

type Props = {
  text: string;
  timestamp?: number;
  align?: 'start' | 'end';
};

function formatTime(ts: number): string {
  const d = new Date(ts);
  return d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
}

export function MessageActionBar({ text, timestamp, align = 'start' }: Props) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    });
  };

  return (
    <div
      className={`pointer-events-none mt-1.5 flex h-6 items-center gap-2 opacity-0 transition-opacity duration-150 group-hover:pointer-events-auto group-hover:opacity-100 ${
        align === 'end' ? 'justify-end' : 'justify-start'
      }`}
    >
      {timestamp && (
        <span className="text-[10px] select-none" style={{ color: 'var(--text-faint)' }}>
          {formatTime(timestamp)}
        </span>
      )}
      {text && (
        <button
          onClick={handleCopy}
          className="flex h-6 w-6 items-center justify-center rounded-full transition-colors"
          style={{ color: 'var(--text-3)' }}
          onMouseEnter={(e) => {
            e.currentTarget.style.background = 'var(--surface-2)';
            e.currentTarget.style.color = 'var(--text)';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.background = 'transparent';
            e.currentTarget.style.color = 'var(--text-3)';
          }}
        >
          {copied ? (
            <Check size={12} style={{ color: 'var(--accent)' }} />
          ) : (
            <Copy size={12} />
          )}
        </button>
      )}
    </div>
  );
}

// desktop/src/vue/components/chat/MessageActionBar.vue
<script setup lang="ts">
// v3.0 — MessageActionBar (Vue 3)
// Direct translation of MessageActionBar.tsx — same Tailwind classes.
import { ref, computed } from 'vue'
import CopyButton from '../shared/CopyButton.vue'

const props = withDefaults(defineProps<{
  copyText?: string
  copyLabel?: string
  align?: 'start' | 'end'
  timestamp?: number
  branchLabel?: string
  branchLoading?: boolean
}>(), {
  copyLabel: 'Copy',
  align: 'start',
  branchLabel: '',
  branchLoading: false,
})

const emit = defineEmits<{ (e: 'branch'): void }>()

const hasCopy = computed(() => Boolean(props.copyText?.trim()))
const hasBranch = computed(() => Boolean(props.branchLabel))

const ts = computed(() => {
  if (typeof props.timestamp !== 'number') return ''
  return new Date(props.timestamp).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })
})
const tsFull = computed(() => {
  if (typeof props.timestamp !== 'number') return ''
  return new Date(props.timestamp).toLocaleString('zh-CN')
})
</script>

<template>
  <div
    v-if="hasCopy || hasBranch"
    data-message-actions
    :data-align="align"
    :class="[
      'pointer-events-none mt-2 flex h-7 w-full opacity-0 transition-opacity duration-150 group-hover:pointer-events-auto group-hover:opacity-100 group-focus-within:pointer-events-auto group-focus-within:opacity-100',
      align === 'end' ? 'justify-end' : 'justify-start',
    ]"
  >
    <div class="flex min-h-7 items-center gap-1.5">
      <CopyButton
        v-if="hasCopy"
        :text="copyText!"
        :label="copyLabel"
        class="inline-flex h-7 w-7 items-center justify-center rounded-full border border-transparent bg-transparent text-[var(--color-text-tertiary)] transition-colors hover:border-[var(--color-brand)]/30 hover:bg-[var(--color-surface-container-low)] hover:text-[var(--color-text-primary)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-brand)]/35"
      >
        <template #default="{ copied }">
          <span v-if="copied" class="material-symbols-outlined text-[14px]">check</span>
          <span v-else class="material-symbols-outlined text-[14px]">content_copy</span>
        </template>
      </CopyButton>
      <button
        v-if="hasBranch"
        type="button"
        :disabled="branchLoading"
        :aria-label="branchLabel"
        :title="branchLabel"
        class="inline-flex h-7 w-7 items-center justify-center rounded-full border border-transparent bg-transparent text-[var(--color-text-tertiary)] transition-colors hover:border-[var(--color-brand)]/30 hover:bg-[var(--color-surface-container-low)] hover:text-[var(--color-text-primary)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-brand)]/35 disabled:cursor-wait disabled:opacity-60"
        @click="emit('branch')"
      >
        <span class="material-symbols-outlined text-[14px]">git_fork</span>
      </button>
      <span
        v-if="ts"
        class="ml-1 inline-flex items-center text-[11px] font-medium tabular-nums text-[var(--color-text-tertiary)]"
        :title="tsFull"
      >{{ ts }}</span>
    </div>
  </div>
</template>
