// frontend/components/chat/UserMessage.tsx
'use client';

import type { Message } from '@/types/chat';
import { MessageActionBar } from './MessageActionBar';

interface UserMessageProps {
  message: Message;
}

export default function UserMessage({ message }: UserMessageProps) {
  return (
    <div className="group flex justify-end">
      <div className="flex min-w-0 max-w-[82%] flex-col items-end">
        {message.attachments && message.attachments.length > 0 && (
          <div className="mb-1 flex flex-wrap gap-1.5 justify-end">
            {message.attachments.filter(a => a.isImage).map((a, i) => (
              <img
                key={i}
                src={a.data}
                alt={a.name}
                className="h-20 w-20 rounded-lg border object-cover"
                style={{ borderColor: 'var(--border)' }}
              />
            ))}
          </div>
        )}
        <div
          className="min-w-0 max-w-full px-4 py-2.5 text-[14px] leading-relaxed whitespace-pre-wrap break-words"
          style={{
            background: 'var(--surface-user-msg)',
            color: 'var(--text)',
            borderRadius: '18px 4px 18px 18px',
            overflowWrap: 'anywhere',
            wordBreak: 'break-word',
          }}
        >
          {message.content}
        </div>
        <MessageActionBar
          text={message.content}
          timestamp={message.timestamp}
          align="end"
        />
      </div>
    </div>
  );
}

// desktop/src/vue/components/chat/UserMessage.vue
<script setup lang="ts">
// v3.0 — UserMessage (Vue 3)
// Direct translation of UserMessage.tsx — same Tailwind classes, same bubble shape.
import { computed } from 'vue'
import MessageActionBar from './MessageActionBar.vue'
import type { ComposerAttachment } from '../../lib/composerAttachments'

const props = defineProps<{
  content: string
  attachments?: ComposerAttachment[]
  branchLabel?: string
  branchLoading?: boolean
  timestamp?: number
}>()

const hasText = computed(() => props.content.trim().length > 0)
</script>

<template>
  <div class="mb-5 flex justify-end">
    <div
      data-message-shell="user"
      class="group flex min-w-0 max-w-[82%] flex-col items-end sm:max-w-[78%] lg:max-w-[72%]"
    >
      <div class="flex max-w-full flex-col items-end gap-2">
        <slot name="attachments" />
        <div
          v-if="hasText"
          class="min-w-0 max-w-full bg-[var(--color-surface-user-msg)] px-4 py-3 text-sm leading-relaxed text-[var(--color-text-primary)] whitespace-pre-wrap break-words"
          style="border-radius: 18px 4px 18px 18px; overflow-wrap: anywhere; word-break: break-word;"
        >
          {{ content }}
        </div>
      </div>
      <MessageActionBar
        v-if="hasText"
        :copy-text="content"
        copy-label="复制提问"
        :branch-label="branchLabel"
        :branch-loading="branchLoading"
        align="end"
        :timestamp="timestamp"
        @branch="$emit('branch')"
      />
    </div>
  </div>
</template>
