// desktop/src/vue/pages/WorkflowsListPage.vue
<!--
  v2.7.0 — WorkflowsListPage (Vue 3 SFC)
  Full translation of src/pages/WorkflowsListPage.tsx (347 lines).
  Shows all saved workflows + create new. Also shows mode library.
-->
<script setup lang="ts">
import { ref, onMounted, type Ref } from 'vue'
import {
  listWorkflows,
  createWorkflow,
  deleteWorkflow,
  runWorkflow,
  type Workflow,
  type NodeTypeMeta,
} from '../api/workflow'
import { listNodeTypes } from '../api/workflow'
import { getApiUrl } from '../api/client'
import { defineAsyncComponent } from 'vue'
const WorkflowEditor = defineAsyncComponent(() => import('../components/WorkflowEditor.vue'))

interface AgentMode {
  id: string
  name: string
  description: string
  category: string
  icon: string
  node_count: number
}

const workflows: Ref<Workflow[]> = ref([])
const nodeTypes: Ref<NodeTypeMeta[]> = ref([])
const editingId: Ref<string | null> = ref(null)
const editingName: Ref<string> = ref('')
const editingNodes: Ref<any[]> = ref([])
const editingEdges: Ref<any[]> = ref([])
const loading: Ref<boolean> = ref(true)
const isRunning: Ref<boolean> = ref(false)
const currentNodeId: Ref<string | null> = ref(null)
const runResult: Ref<string | null> = ref(null)
const modes: Ref<AgentMode[]> = ref([])

const refresh = async () => {
  loading.value = true
  try {
    const [list, types, modesData] = await Promise.all([
      listWorkflows(),
      listNodeTypes(),
      fetch(getApiUrl('/api/workflows/modes'))
        .then(r => r.json())
        .then(d => d.modes || [])
        .catch(() => []),
    ])
    workflows.value = list
    nodeTypes.value = types
    modes.value = modesData
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  refresh()
})

const handleNew = async () => {
  // v2.7.0: Always include start + end nodes; LLM node added in editor.
  // Don't depend on nodeTypes.length — if the metadata API was
  // slow / failed, the user can still create a workflow.
  const wf = await createWorkflow({
    name: '未命名工作流',
    description: '',
    nodes: [
      { id: 'start-1', type: 'start', position: { x: 100, y: 200 }, data: { label: '开始' } },
      { id: 'end-1', type: 'end', position: { x: 500, y: 200 }, data: { label: '结束' } },
    ],
    edges: [],
  } as any)
  await refresh()
  editingId.value = (wf as any).id
  editingName.value = (wf as any).name
  editingNodes.value = (wf as any).nodes
  editingEdges.value = (wf as any).edges
}

const handleEdit = (wf: Workflow) => {
  editingId.value = wf.id
  editingName.value = wf.name
  editingNodes.value = wf.nodes as any[]
  editingEdges.value = wf.edges as any[]
}

const handleDelete = async (id: string) => {
  if (!confirm('确定删除这个工作流？')) return
  await deleteWorkflow(id)
  await refresh()
}

const handleSave = async (nodes: any[], edges: any[]) => {
  if (!editingId.value) return
  const r = await fetch(`/api/workflows/${editingId.value}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      name: editingName.value,
      nodes: nodes.map((n: any) => ({
        id: n.id,
        type: n.type,
        position: n.position,
        data: n.data,
      })),
      edges: edges.map((e: any) => ({
        id: e.id,
        source: e.source,
        target: e.target,
      })),
    }),
  })
  if (!r.ok) throw new Error(`Save failed: ${r.status}`)
  await refresh()
}

const handleRun = async () => {
  if (!editingId.value) return
  isRunning.value = true
  currentNodeId.value = null
  runResult.value = null
  try {
    const run = await runWorkflow(editingId.value, { input: '你好' })
    runResult.value = JSON.stringify(run, null, 2)
  } catch (e: any) {
    runResult.value = `Error: ${e.message}`
  } finally {
    isRunning.value = false
  }
}

const handleBack = async () => {
  editingId.value = null
  editingName.value = ''
  editingNodes.value = []
  editingEdges.value = []
  runResult.value = null
  await refresh()
}
</script>

<template>
  <!-- Editing mode: show WorkflowEditor full-screen -->
  <div v-if="editingId" style="width: 100%; height: 100vh">
    <WorkflowEditor
      :workflowId="editingId"
      :workflowName="editingName"
      :initialNodes="editingNodes"
      :initialEdges="editingEdges"
      :onSave="handleSave"
      :onRun="handleRun"
      :isRunning="isRunning"
      :currentNodeId="currentNodeId"
      :onBack="handleBack"
    />
    <!-- Run result floating panel (createPortal → teleport) -->
    <Teleport to="body">
      <div
        v-if="runResult"
        @click="runResult = null"
        style="
          position: fixed;
          bottom: 16px;
          left: 50%;
          transform: translateX(-50%);
          background: var(--color-surface);
          border: 1px solid var(--color-border);
          border-radius: 8px;
          padding: 16px;
          max-width: 720px;
          max-height: 240px;
          overflow: auto;
          box-shadow: 0 4px 16px rgba(0,0,0,0.15);
          font-size: 12px;
          font-family: monospace;
          color: var(--color-text-primary);
          white-space: pre-wrap;
          z-index: 50;
        "
      >
        <strong>运行结果 (点击关闭):</strong>
        <pre style="margin: 8px 0 0; font-size: 11px">{{ runResult }}</pre>
      </div>
    </Teleport>
  </div>

  <!-- List mode: workflows + mode library -->
  <div
    v-else
    style="
      max-width: 960px;
      margin: 0 auto;
      padding: 40px 20px;
      color: var(--color-text-primary);
      height: 100%;
      overflow-y: auto;
    "
  >
    <!-- Header -->
    <div
      style="
        display: flex;
        align-items: center;
        justify-content: space-between;
        margin-bottom: 24px;
      "
    >
      <h1 style="font-size: 24px; font-weight: 700; margin: 0">工作流</h1>
      <button
        @click="handleNew"
        style="
          padding: 8px 16px;
          background: var(--color-brand);
          color: #fff;
          border: none;
          border-radius: 4px;
          cursor: pointer;
          font-weight: 600;
          font-size: 14px;
          opacity: nodeTypes.length === 0 ? 0.7 : 1;
        "
      >
        + 新建工作流
      </button>
    </div>

    <!-- Loading state -->
    <div v-if="loading" style="color: var(--color-text-secondary)">加载中…</div>

    <!-- Empty state -->
    <div
      v-else-if="workflows.length === 0"
      style="
        padding: 40px 20px;
        text-align: center;
        color: var(--color-text-secondary);
        background: var(--color-surface-container-low);
        border-radius: 8px;
      "
    >
      还没有工作流。点"新建工作流"创建一个。
    </div>

    <!-- Workflows grid -->
    <div
      v-else
      style="display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 16px"
    >
      <div
        v-for="wf in workflows"
        :key="wf.id"
        @click="handleEdit(wf)"
        style="
          background: var(--color-surface);
          border: 1px solid var(--color-border);
          border-radius: 8px;
          padding: 16px;
          cursor: pointer;
        "
      >
        <div style="font-size: 15px; font-weight: 600; margin-bottom: 4px">{{ wf.name }}</div>
        <div
          style="font-size: 12px; color: var(--color-text-tertiary); margin-bottom: 12px"
        >
          {{ wf.description || '无描述' }} · {{ wf.nodes.length }} 节点 · v{{ wf.version }}
        </div>
        <div style="display: flex; gap: 8px">
          <button
            @click.stop="handleEdit(wf)"
            style="
              padding: 4px 10px;
              background: var(--color-surface-container-high);
              border: 1px solid var(--color-border);
              border-radius: 4px;
              color: var(--color-text-primary);
              cursor: pointer;
              font-size: 12px;
            "
          >
            编辑
          </button>
          <button
            @click.stop="handleDelete(wf.id)"
            style="
              padding: 4px 10px;
              background: transparent;
              border: 1px solid #ef4444;
              color: #ef4444;
              border-radius: 4px;
              cursor: pointer;
              font-size: 12px;
            "
          >
            删除
          </button>
        </div>
      </div>
    </div>

    <!-- Mode library -->
    <h2 style="font-size: 18px; font-weight: 700; margin: 32px 0 16px">模式库</h2>
    <div
      style="display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 12px"
    >
      <div
        v-for="mode in modes"
        :key="mode.id"
        style="
          background: var(--color-surface);
          border: 1px solid var(--color-border);
          border-radius: 8px;
          padding: 14px;
        "
      >
        <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 6px">
          <span
            style="font-size: 18px; font-weight: 600; color: var(--color-brand)"
            v-text="
              mode.id === 'single_agent'
                ? '1'
                : mode.id === 'sequential'
                  ? '→'
                  : mode.id === 'parallel'
                    ? '∥'
                    : mode.id === 'loop'
                      ? '↻'
                      : mode.id === 'review_critique'
                        ? '✓'
                        : mode.id === 'iterative_refine'
                          ? '↑'
                          : mode.id === 'coordinator'
                            ? '◎'
                            : mode.id === 'hierarchical'
                              ? '⊞'
                              : mode.id === 'swarm'
                                ? '∞'
                                : mode.id === 'react'
                                  ? '◉'
                                  : mode.id === 'human_in_loop'
                                    ? '◎'
                                    : '⚙'
            "
          ></span>
          <span style="font-size: 14px; font-weight: 600">{{ mode.name }}</span>
        </div>
        <div
          style="
            font-size: 12px;
            color: var(--color-text-tertiary);
            margin-bottom: 10px;
            line-height: 1.4;
          "
        >
          {{ mode.description }}
        </div>
        <div
          style="font-size: 11px; color: var(--color-text-disabled); margin-bottom: 8px"
        >
          {{ mode.node_count }} 节点 ·
          {{
            mode.category === 'basic'
              ? '基础'
              : mode.category === 'multi_agent'
                ? '多 Agent'
                : '高级'
          }}
        </div>
        <button
          @click="
            async () => {
              try {
                const r = await fetch(
                  getApiUrl(`/api/workflows/modes/${mode.id}/instantiate`),
                  { method: 'POST' }
                )
                if (r.ok) {
                  const wf = await r.json()
                  handleEdit(wf)
                  await refresh()
                }
              } catch {}
            }
          "
          style="
            padding: 4px 12px;
            background: var(--color-brand);
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 12px;
            font-weight: 600;
          "
        >
          使用此模式
        </button>
      </div>
    </div>
  </div>
</template>

// desktop/src/pages/WorkflowsListPage.tsx
// v2.7.0 — WorkflowsListPage: shows all saved workflows + create new.

import { useEffect, useState } from 'react'
import {
  listWorkflows,
  createWorkflow,
  deleteWorkflow,
  runWorkflow,
  type Workflow,
  type NodeTypeMeta,
} from '../api/workflow'
import { listNodeTypes } from '../api/workflow'
import { WorkflowEditor } from '../components/workflow/WorkflowEditor'
import type { Edge, Node } from '@xyflow/react'
import { getApiUrl } from '../api/client'

interface AgentMode {
  id: string
  name: string
  description: string
  category: string
  icon: string
  node_count: number
}

export function WorkflowsListPage() {
  const [workflows, setWorkflows] = useState<Workflow[]>([])
  const [nodeTypes, setNodeTypes] = useState<NodeTypeMeta[]>([])
  const [editingId, setEditingId] = useState<string | null>(null)
  const [editingName, setEditingName] = useState<string>('')
  const [editingNodes, setEditingNodes] = useState<Node[]>([])
  const [editingEdges, setEditingEdges] = useState<Edge[]>([])
  const [loading, setLoading] = useState(true)
  const [isRunning, setIsRunning] = useState(false)
  const [currentNodeId, setCurrentNodeId] = useState<string | null>(null)
  const [runResult, setRunResult] = useState<string | null>(null)
  const [modes, setModes] = useState<AgentMode[]>([])

  const refresh = async () => {
    setLoading(true)
    try {
      const [list, types, modesData] = await Promise.all([
        listWorkflows(),
        listNodeTypes(),
        fetch(getApiUrl('/api/workflows/modes')).then(r => r.json()).then(d => d.modes || []).catch(() => []),
      ])
      setWorkflows(list)
      setNodeTypes(types)
      setModes(modesData)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    refresh()
  }, [])

  const handleNew = async () => {
    // v2.7.0: Always include start + end nodes; LLM node added in editor.
    // Don't depend on nodeTypes.length — if the metadata API was
    // slow / failed, the user can still create a workflow.
    const wf = await createWorkflow({
      name: '未命名工作流',
      description: '',
      nodes: [
        { id: 'start-1', type: 'start', position: { x: 100, y: 200 }, data: { label: '开始' } },
        { id: 'end-1', type: 'end', position: { x: 500, y: 200 }, data: { label: '结束' } },
      ],
      edges: [],
    })
    await refresh()
    setEditingId(wf.id)
    setEditingName(wf.name)
    setEditingNodes(wf.nodes as unknown as Node[])
    setEditingEdges(wf.edges as unknown as Edge[])
  }

  const handleEdit = (wf: Workflow) => {
    setEditingId(wf.id)
    setEditingName(wf.name)
    setEditingNodes(wf.nodes as unknown as Node[])
    setEditingEdges(wf.edges as unknown as Edge[])
  }

  const handleDelete = async (id: string) => {
    if (!confirm('确定删除这个工作流？')) return
    await deleteWorkflow(id)
    await refresh()
  }

  const handleSave = async (nodes: Node[], edges: Edge[]) => {
    if (!editingId) return
    const r = await fetch(`/api/workflows/${editingId}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        name: editingName,
        nodes: nodes.map((n) => ({
          id: n.id,
          type: n.type,
          position: n.position,
          data: n.data,
        })),
        edges: edges.map((e) => ({
          id: e.id,
          source: e.source,
          target: e.target,
        })),
      }),
    })
    if (!r.ok) throw new Error(`Save failed: ${r.status}`)
    await refresh()
  }

  const handleRun = async () => {
    if (!editingId) return
    setIsRunning(true)
    setCurrentNodeId(null)
    setRunResult(null)
    try {
      const run = await runWorkflow(editingId, { input: '你好' })
      setRunResult(JSON.stringify(run, null, 2))
    } catch (e) {
      setRunResult(`Error: ${(e as Error).message}`)
    } finally {
      setIsRunning(false)
    }
  }

  const handleBack = async () => {
    setEditingId(null)
    setEditingName('')
    setEditingNodes([])
    setEditingEdges([])
    setRunResult(null)
    await refresh()
  }

  if (editingId) {
    return (
      <div style={{ width: '100%', height: '100vh' }}>
        <WorkflowEditor
          workflowId={editingId}
          workflowName={editingName}
          initialNodes={editingNodes}
          initialEdges={editingEdges}
          onSave={handleSave}
          onRun={handleRun}
          isRunning={isRunning}
          currentNodeId={currentNodeId}
          onBack={handleBack}
        />
        {runResult && (
          <div
            style={{
              position: 'fixed',
              bottom: 16,
              left: '50%',
              transform: 'translateX(-50%)',
              background: 'var(--color-surface)',
              border: '1px solid var(--color-border)',
              borderRadius: 8,
              padding: 16,
              maxWidth: 720,
              maxHeight: 240,
              overflow: 'auto',
              boxShadow: '0 4px 16px rgba(0,0,0,0.15)',
              fontSize: 12,
              fontFamily: 'monospace',
              color: 'var(--color-text-primary)',
              whiteSpace: 'pre-wrap',
              zIndex: 50,
            }}
            onClick={() => setRunResult(null)}
          >
            <strong>运行结果 (点击关闭):</strong>
            <pre style={{ margin: '8px 0 0', fontSize: 11 }}>{runResult}</pre>
          </div>
        )}
      </div>
    )
  }

  return (
    <div
      style={{
        maxWidth: 960,
        margin: '0 auto',
        padding: '40px 20px',
        color: 'var(--color-text-primary)',
        height: '100%',
        overflowY: 'auto',
      }}
    >
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          marginBottom: 24,
        }}
      >
        <h1 style={{ fontSize: 24, fontWeight: 700, margin: 0 }}>工作流</h1>
        <button
          onClick={handleNew}
          style={{
            padding: '8px 16px',
            background: 'var(--color-brand)',
            color: '#fff',
            border: 'none',
            borderRadius: 4,
            cursor: 'pointer',
            fontWeight: 600,
            fontSize: 14,
            opacity: nodeTypes.length === 0 ? 0.7 : 1,
          }}
        >
          + 新建工作流
        </button>
      </div>

      {loading ? (
        <div style={{ color: 'var(--color-text-secondary)' }}>加载中…</div>
      ) : workflows.length === 0 ? (
        <div
          style={{
            padding: '40px 20px',
            textAlign: 'center',
            color: 'var(--color-text-secondary)',
            background: 'var(--color-surface-container-low)',
            borderRadius: 8,
          }}
        >
          还没有工作流。点"新建工作流"创建一个。
        </div>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 16 }}>
          {workflows.map((wf) => (
            <div
              key={wf.id}
              style={{
                background: 'var(--color-surface)',
                border: '1px solid var(--color-border)',
                borderRadius: 8,
                padding: 16,
                cursor: 'pointer',
              }}
              onClick={() => handleEdit(wf)}
            >
              <div style={{ fontSize: 15, fontWeight: 600, marginBottom: 4 }}>{wf.name}</div>
              <div style={{ fontSize: 12, color: 'var(--color-text-tertiary)', marginBottom: 12 }}>
                {wf.description || '无描述'} · {wf.nodes.length} 节点 · v{wf.version}
              </div>
              <div style={{ display: 'flex', gap: 8 }}>
                <button
                  onClick={(e) => {
                    e.stopPropagation()
                    handleEdit(wf)
                  }}
                  style={{
                    padding: '4px 10px',
                    background: 'var(--color-surface-container-high)',
                    border: '1px solid var(--color-border)',
                    borderRadius: 4,
                    color: 'var(--color-text-primary)',
                    cursor: 'pointer',
                    fontSize: 12,
                  }}
                >
                  编辑
                </button>
                <button
                  onClick={(e) => {
                    e.stopPropagation()
                    handleDelete(wf.id)
                  }}
                  style={{
                    padding: '4px 10px',
                    background: 'transparent',
                    border: '1px solid #ef4444',
                    color: '#ef4444',
                    borderRadius: 4,
                    cursor: 'pointer',
                    fontSize: 12,
                  }}
                >
                  删除
                </button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* 模式库 */}
      <h2 style={{ fontSize: 18, fontWeight: 700, margin: '32px 0 16px' }}>模式库</h2>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))', gap: 12 }}>
        {modes.map((mode) => (
          <div
            key={mode.id}
            style={{
              background: 'var(--color-surface)',
              border: '1px solid var(--color-border)',
              borderRadius: 8,
              padding: 14,
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
              <span style={{ fontSize: 18, fontWeight: 600, color: 'var(--color-brand)' }}>{mode.id === 'single_agent' ? '1' : mode.id === 'sequential' ? '→' : mode.id === 'parallel' ? '∥' : mode.id === 'loop' ? '↻' : mode.id === 'review_critique' ? '✓' : mode.id === 'iterative_refine' ? '↑' : mode.id === 'coordinator' ? '◎' : mode.id === 'hierarchical' ? '⊞' : mode.id === 'swarm' ? '∞' : mode.id === 'react' ? '◉' : mode.id === 'human_in_loop' ? '◎' : '⚙'}</span>
              <span style={{ fontSize: 14, fontWeight: 600 }}>{mode.name}</span>
            </div>
            <div style={{ fontSize: 12, color: 'var(--color-text-tertiary)', marginBottom: 10, lineHeight: 1.4 }}>
              {mode.description}
            </div>
            <div style={{ fontSize: 11, color: 'var(--color-text-disabled)', marginBottom: 8 }}>
              {mode.node_count} 节点 · {mode.category === 'basic' ? '基础' : mode.category === 'multi_agent' ? '多 Agent' : '高级'}
            </div>
            <button
              onClick={async () => {
                try {
                  const r = await fetch(getApiUrl(`/api/workflows/modes/${mode.id}/instantiate`), { method: 'POST' })
                  if (r.ok) {
                    const wf = await r.json()
                    handleEdit(wf)
                    await refresh()
                  }
                } catch {}
              }}
              style={{
                padding: '4px 12px',
                background: 'var(--color-brand)',
                color: '#fff',
                border: 'none',
                borderRadius: 4,
                cursor: 'pointer',
                fontSize: 12,
                fontWeight: 600,
              }}
            >
              使用此模式
            </button>
          </div>
        ))}
      </div>
    </div>
  )
}
