// desktop/src/vue/components/chat/ThinkingBlock.vue
<script setup lang="ts">
// v3.0 — ThinkingBlock (Vue 3)
// Direct translation of ThinkingBlock.tsx — same Tailwind classes, same animations.
import { ref, computed, watch, nextTick } from 'vue'

const props = withDefaults(defineProps<{
  content: string
  isActive?: boolean
}>(), {
  isActive: false,
})

const expanded = ref(false)
const contentRef = ref<HTMLDivElement | null>(null)

const displayContent = computed(() => props.content.replace(/\r\n?/g, '\n').trimEnd())
const hasContent = computed(() => displayContent.value.trim().length > 0)

watch([() => props.content, expanded], async () => {
  if (expanded.value && props.isActive) {
    await nextTick()
    if (contentRef.value) contentRef.value.scrollTop = contentRef.value.scrollHeight
  }
})
</script>

<template>
  <div class="mb-1">
    <button
      type="button"
      @click="expanded = !expanded"
      :aria-expanded="expanded"
      class="flex w-full items-center gap-1.5 rounded-md px-1 py-0.5 text-left text-[12px] text-[var(--color-text-tertiary)] transition-colors hover:text-[var(--color-text-secondary)]"
    >
      <span class="text-[10px] text-[var(--color-outline)]">
        {{ expanded ? '▾' : '▸' }}
      </span>
      <span class="shrink-0 font-medium italic">
        {{ isActive ? '思考中' : '思考过程' }}
        <span v-if="isActive" class="thinking-dots" />
      </span>
    </button>
    <div
      v-if="expanded && hasContent"
      ref="contentRef"
      data-thinking-content="expanded"
      class="relative mt-1 max-h-[300px] overflow-y-auto rounded-lg border border-[var(--color-border)]/40 bg-[var(--color-surface-container-lowest)] p-2.5 text-[11px] text-[var(--color-text-secondary)]"
    >
      <pre class="thinking-markdown whitespace-pre-wrap break-words font-sans">{{ displayContent }}</pre>
      <span v-if="isActive" class="thinking-cursor" />
    </div>
  </div>
</template>

<style>
@keyframes thinking-cursor-blink {
  0%, 100% { opacity: 1; }
  50% { opacity: 0; }
}
@keyframes thinking-dots-anim {
  0%, 20% { content: ''; }
  40% { content: '.'; }
  60% { content: '..'; }
  80%, 100% { content: '...'; }
}
.thinking-cursor {
  display: inline-block; width: 2px; height: 1em;
  background: var(--color-text-tertiary);
  vertical-align: middle; margin-left: 1px;
  animation: thinking-cursor-blink 1s step-end infinite;
}
.thinking-dots::after {
  content: ''; animation: thinking-dots-anim 1.4s steps(1, end) infinite;
}
</style>

// frontend/components/chat/ThinkingBlock.tsx
'use client';

import { useState } from 'react';
import { ChevronDown, ChevronRight, Brain } from 'lucide-react';
import MarkdownRenderer from '@/components/markdown/MarkdownRenderer';

interface ThinkingBlockProps {
  content: string;
  isStreaming?: boolean;
  defaultCollapsed?: boolean;
}

export default function ThinkingBlock({
  content,
  isStreaming = false,
  defaultCollapsed = true,
}: ThinkingBlockProps) {
  const [collapsed, setCollapsed] = useState(defaultCollapsed);

  return (
    <div
      className="my-2 rounded-lg border border-[var(--border)] overflow-hidden animate-fade-in"
      style={{ background: 'var(--moon-bg)' }}
    >
      {/* Header */}
      <button
        onClick={() => setCollapsed((c) => !c)}
        className="flex w-full items-center gap-1.5 px-3 py-2 text-[13px] font-medium transition-colors hover:bg-[var(--surface-2)]"
        style={{ color: 'var(--moon)' }}
      >
        {collapsed ? (
          <ChevronRight size={14} />
        ) : (
          <ChevronDown size={14} />
        )}
        <Brain size={14} />
        <span className={isStreaming ? 'thinking-dots' : ''}>推理过程</span>
        {isStreaming && (
          <span className="ml-auto flex items-center gap-1 text-[11px] text-[var(--text-3)]">
            <span className="inline-block h-1.5 w-1.5 rounded-full bg-[var(--moon)] animate-pulse" />
            生成中
          </span>
        )}
      </button>

      {/* Content */}
      {!collapsed && (
        <div
          className="max-h-[300px] overflow-y-auto border-t border-[var(--border)] px-3 py-2"
        >
          <div className="font-mono text-[13px] text-[var(--text-2)] whitespace-pre-wrap">
            <MarkdownRenderer content={content || '（无内容）'} />
          </div>
        </div>
      )}
    </div>
  );
}
